[package]
authors.workspace = true
description = "An opinionated shell with a focus on simplicity and performance"
documentation = "https://docs.rs/smash"
edition.workspace = true
license = "MIT"
name = "smash"
readme = "README.md"
version = "0.1.0"

# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["paste"]
paste = []

[dependencies]
clap = "4.5.40"
classic = { path = "lib/classic" }
crossterm = { version = "0.28.1", features = ["events"] }
ctrlc = "3.4.7"
hostname = "0.4.1"
shellexpand = "3.1.0"
which = "7.0.2"

# [workspace]
# members = ["lib/classic"]

[workspace.package]
authors = ["Julien Montagut <_@julienmontagut.com>"]
edition = "2021"
